import type { Metadata } from "next";
import { Inter, Poppins, Righteous } from "next/font/google";
import "./globals.css";
import CustomThemeProvider from "../providers/CustomThemeProvider";
import Navbar from "../components/Navbar";

const righteous = Righteous({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-righteous",
});

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${righteous.variable} ${poppins.variable} ${inter.variable}`}
    >
      <body
        className={`${poppins.className} h-full bg-amber-50 text-indigo-500 dark:bg-slate-950 dark:text-amber-50`}
      >
        <CustomThemeProvider>
          <Navbar />
          <main className="mx-auto max-w-5xl px-6">{children}</main>
        </CustomThemeProvider>
      </body>
    </html>
  );
}
